added

diff --git a/.githooks/pre-commit/commit-msg b/.githooks/pre-commit/commit-msg
--- a/.githooks/pre-commit/commit-msg
+++ b/.githooks/pre-commit/commit-msg
@@ -1,17 +1,28 @@
 #!/bin/sh
 
 # set this to your active development branch
-develop_branch="develop"
-current_branch="$(git rev-parse --abbrev-ref HEAD)"
+#develop_branch="develop"
+#current_branch="$(git rev-parse --abbrev-ref HEAD)"
 
 # only check commit messages on main development branch
-[ "$current_branch" != "$develop_branch" ] && exit 0
+#[ "$current_branch" != "$develop_branch" ] && exit 0
 
 # regex to validate in commit msg
 commit_regex='(wap-[0-9]+|merge)'
 error_msg="Aborting commit. Your commit message is missing either a JIRA Issue ('WAP-1111') or 'Merge'"
-
-if ! grep -iqE "$commit_regex" "$1"; then
-    echo "$error_msg" >&2
+echo "$1"
+MESSAGE=$(git log -1 HEAD --pretty=format:%s)
+echo "$MESSAGE"
+#if ! grep -iqE "$commit_regex" "$MESSAGE"; then
+if [[ ${commit_regex} != ${$MESSAGE} ]]; then 
+   echo "$error_msg" >&2
     exit 1
 fi
+
+#MSG="$1"
+
+#if ! grep -qE "updated" "$MSG";then
+#    cat "$MSG"
+#    echo "Your commit message must contain the word 'updated'"
+ #   exit 1
+#fi
