jhkjhoijuiojnkojoioajlksajdjsoiajdjiojojlomnsnjoijlkoisajajijwoiuoijjaljoijoisajsjadjoijuosijsllsajsjidjidajsljdijsdij

diff --git a/.githooks/pre-commit/pre-commit b/.githooks/pre-commit/pre-commit
--- a/.githooks/pre-commit/pre-commit
+++ b/.githooks/pre-commit/pre-commit
@@ -1,45 +1,17 @@
 #!/bin/sh
-#
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-commit".
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+# set this to your active development branch
+#develop_branch="develop"
+#current_branch="$(git rev-parse --abbrev-ref HEAD)"
+
+# only check commit messages on main development branch
+#[ "$current_branch" != "$develop_branch" ] && exit 0
+
+# regex to validate in commit msg
+commit_regex='(DEVOPS-[0-9]+|updated)'
+error_msg="Aborting commit. Your commit message is missing either a JIRA Issue ('DEVOPS-1111') or 'updated'"
+
+if ! grep -iqE "$commit_regex" "$1"; then
+    echo "$error_msg" >&2
+    exit 1
 fi
-
-# If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --bool hooks.allownonascii)
-
-# Redirect output to stderr.
-exec 1>&2
-
-# Cross platform projects tend to avoid non-ASCII filenames; prevent
-# them from being added to the repository. We exploit the fact that the
-# printable range starts at the space character and ends with tilde.
-if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
-This can cause problems if you want to work with people on other platforms.
-To be portable it is advisable to rename the file.
-If you know what you are doing you can disable this check using:
-  git config hooks.allownonascii true
-EOF
-	exit 1
-fi
-
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
